---

- name: add twemproxy group
  group: name=twemproxy

- name: add twemproxy user
  user: name=twemproxy group=twemproxy shell=/usr/sbin/nologin

- name: mkdir conf
  file: path="/usr/local/twemproxy/conf"
        state=directory
        group=twemproxy
        owner=twemproxy
        mode=0755

- name: install gcc
  yum:
    name: gcc
    state: present

- name: install automake
  yum:
    name: automake
    state: present

- name: install autoconf
  yum:
    name: autoconf
    state: present

- name: install libtool
  yum:
    name: libtool
    state: present

- name: check twemproxy install
  stat: path=/usr/local/twemproxy/sbin/nutcracker
  register: exist_twemproxy

- name: download twemproxy src
  get_url: url=https://github.com/twitter/twemproxy/archive/v0.4.1.tar.gz dest=/usr/local/src/twemproxy-0.4.1.tar.gz
  when: exist_twemproxy.stat.exists == false

- name: extract twemproxy archive
  command: tar xzf twemproxy-0.4.1.tar.gz chdir=/usr/local/src creates=usr/local/src/twemproxy-0.4.1
  when: exist_twemproxy.stat.exists == false

- name: autoconf
  command: autoconf -fvi chdir=/usr/local/src/twemproxy-0.4.1
  when: exist_twemproxy.stat.exists == false
  ignore_errors: True

- name: configure twemproxy
  command: >
    ./configure
    --enable-debug=log
    --prefix=/usr/local/twemproxy
    --user=twemproxy
    --group=twemproxy
    chdir=/usr/local/src/twemproxy-0.4.1
  when: exist_twemproxy.stat.exists == false

- name: make twemproxy
  command: make chdir=/usr/local/src/twemproxy-0.4.1
  when: exist_twemproxy.stat.exists == false

- name: install twemproxy
  command: make install chdir=/usr/local/src/twemproxy-0.4.1
  when: exist_twemproxy.stat.exists == false

- name: put twemproxy.conf
  template:
    src: twemproxy.conf.j2
    dest: /usr/local/twemproxy/conf/twemproxy.conf
  tags:
    - twemproxy:config
  notify: ['Restart twemproxy']

- name: put init script
  template:
    src: twemproxy.init.j2
    dest: /etc/init.d/twemproxy
    mode: 755
  when: exist_twemproxy.stat.exists == false

- name: register service twemproxy
  service:
    name: twemproxy
    state: started
    enabled: yes

